// Import TutorLoop seed data generated by scripts/generate_mongodb_data.py
//
// Usage:
//   1. python scripts/generate_mongodb_data.py
//   2. mongosh "<your-atlas-uri>/tutorloop" scripts/import_mongodb_data.js
//
// Or from Atlas shell: load("scripts/import_mongodb_data.js")

const dataDir = "scripts/mongodb_data";
const collections = [
  "users",
  "tutors",
  "notes",
  "books",
  "book_chunks",
  "purchases",
  "bookings",
  "sessions",
  "transcripts",
  "ai_conversations",
  "ai_reflections",
  "student_learning_profiles",
  "recommendations",
  "reviews",
];

function loadJson(relativePath) {
  return JSON.parse(cat(relativePath));
}

print("Clearing TutorLoop collections...");
for (const name of collections) {
  db.getCollection(name).deleteMany({});
}

print("Importing JSON documents...");
for (const name of collections) {
  const path = `${dataDir}/${name}.json`;
  const docs = loadJson(path);
  if (!docs.length) {
    print(`  ${name}: skipped (empty)`);
    continue;
  }
  db.getCollection(name).insertMany(docs);
  print(`  ${name}: ${docs.length}`);
}

print("Creating indexes...");
load("scripts/mongodb_atlas_indexes.js");

print("TutorLoop import complete.");
